### ISSUE TITLE
[UI] Allow for Larger (Smaller) number of items

### ISSUE THREAD

**Issue by arkaray** [sharmaeklavya2/packing-game#7] opened 2020-08-29 07:36 UTC
Slider/Text box both should work.

**Comment by arkaray** [comment] 2020-08-29 07:42
This should also address the issue of the problem of being easily solvable as mentioned in exchanges in #4 to some extent.

**Comment by sharmaeklavya2** [comment] 2020-08-30 08:38
I think choosing more items should (for now) only be allowed while specifying parameters for loading a new game. We already have the functionality for that: the random instance generator `bp1` supports it and the querystring parameter `n` can be used to specify it (https://sharmaeklavya2.github.io/packing-game/?srctype=gen&src=bp1&n=100).

What we don't have is a UI for "load new game". We can have a text-box/slider for number of items in that UI. Closing this as a duplicate of #5. Feel free to reopen this issue if you disagree with anything I said here.

**Closed as completed by sharmaeklavya2** 2020-08-30 08:38 UTC
Labels: duplicate
